export const SET_CURRENT_BLOCK_LOADING = 'SET_CURRENT_BLOCK_LOADING';
export const SET_CURRENT_BLOCK_ITEM = 'SET_CURRENT_BLOCK_ITEM';
export const GET_CURRENT_BLOCK_ERROR = 'GET_CURRENT_BLOCK_ERROR';

export const SET_LATEST_BLOCK_LOADING = 'SET_LATEST_BLOCK_LOADING';
export const SET_LATEST_BLOCK_ITEM = 'SET_LATEST_BLOCK_ITEM';
export const GET_LATEST_BLOCK_ERROR = 'GET_LATEST_BLOCK_ERROR';
